table-of-contents: 
 - destination: Europe
   text: Top 10 Places to Go
 - destination: Australia
   text: Top 10 Places to Go
 - destination: Asia
   text: Top 10 Places to Go
 - destination: Europe
   text: Top 10 Places to Go